### ISSUE TITLE
Meta integration tab blank

### ISSUE THREAD

**Issue by eduromanc** [efeone/frappe_meta_integration#24]
Hi teams,

I install this APP on ERPnext and have this issue.
I try uninstall and install but I get same problem.

this is my version:
![image](https://user-images.githubusercontent.com/69904374/215364538-e91148ac-da96-40a1-a4c2-78a95fc98db2.png)

this is the error
![image](https://user-images.githubusercontent.com/69904374/215364585-982e7c95-0bc7-4024-9c8c-50e923d77e2f.png)

any idea to try fix it?
thank in advance

**Comment by SherinKR** [comment]
Checkout to version-2 branch and take latest pull, which is compatible with version-14 of frappe. Then do bench migrate.

**Comment by eduromanc** [comment]
Hi SherinKR, 

I was move to branch "version-2" whit command:

bench switch-to-branch version-2 frappe_meta_integration
bench --site mysite migrate (Don't work)
and 
bench update --patch (try with this, but don't work)

Do I need uninstall old version and install again.


![image](https://user-images.githubusercontent.com/69904374/215471958-5cf91ba1-76b9-4fc7-8ca4-5817332564f0.png)

thank for your help!

**Comment by SherinKR** [comment]
Issue can't bereplicated in other versions
