### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NayanGajjar** [efeone/frappe_meta_integration#26]
getting below error 9n campaign while attaching any attachments like doc or image

![image](https://github.com/efeone/frappe_meta_integration/assets/122445476/ced06ea5-f824-43d0-9c22-3f7abb33bcc2)

Frappe and app version

![image](https://github.com/efeone/frappe_meta_integration/assets/122445476/0cf1912d-5733-4b3c-9e27-054047ca7000)

![image](https://github.com/efeone/frappe_meta_integration/assets/122445476/f15d9e4c-8cf9-4bf0-8924-0c564a15f4e0)

Regards,
Nayan

**Comment by SherinKR** [comment]
Fixed on later updates.
